# Generated by Django 5.2.6 on 2025-09-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "-created_at"],
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта"),
                    ("can_publish_product", "Может публиковать продукт"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
